all: aufgabe5_1 aufgabe5_2

aufgabe5_1:
	$(CC) -Wall -lm -o aufgabe5_1_binary aufgabe5_1.c

aufgabe5_2:
	$(CC) -Wall -lm -o aufgabe5_2_binary aufgabe5_2.c

clean:
	rm aufgabe5_1_binary aufgabe5_2_binary
