all: aufgabe1 aufgabe2 aufgabe3 aufgabe4 aufgabe5

aufgabe1:
	 $(CC) -Wall -o aufgabe1 aufgabe1.c

aufgabe2:
	 $(CC) -Wall -o aufgabe2 aufgabe2.c

aufgabe3:
	 $(CC) -Wall -o aufgabe3 aufgabe3.c

aufgabe4:
	 $(CC) -Wall -lm -o aufgabe4 aufgabe4.c

aufgabe5:
	 $(CC) -Wall -lm -o aufgabe5 aufgabe5.c

clean:
	rm aufgabe1 aufgabe2 aufgabe3 aufgabe4 aufgabe5
