all: aufgabe1 aufgabe2 aufgabe3 aufgabe4 aufgabe5

aufgabe1:
	 $(CC) -Wall -o aufgabe1_binary aufgabe1.c

aufgabe2:
	 $(CC) -Wall -o aufgabe2_binary aufgabe2.c

aufgabe3:
	 $(CC) -Wall -o aufgabe3_binary aufgabe3.c

aufgabe4:
	 $(CC) -Wall -lm -o aufgabe4_binary aufgabe4.c

aufgabe5:
	 $(CC) -Wall -lm -o aufgabe5_binary aufgabe5.c

clean:
	rm aufgabe1_binary aufgabe2_binary aufgabe3_binary aufgabe4_binary aufgabe5_binary
