all: aufgabe6_1 aufgabe6_3

aufgabe6_1:
	$(CC) -Wall -lm -o aufgabe6_1_binary aufgabe6_1.c

aufgabe6_3:
	$(CC) -Wall -lm -o aufgabe6_3_binary aufgabe6_3.c

clean:
	rm aufgabe6_1_binary aufgabe6_3_binary
